In [23]:
#신경망 첫걸음 - 시그모이드값 및 최종 출력값 확인 p93
import numpy
import scipy.special

activation_function = lambda x: scipy.special.expit(x)

I = [[0.9],
     [0.1],
     [0.8]]
W_input_hidden = [[0.9,0.3,0.4],
                  [0.2,0.8,0.2],
                  [0.1,0.5,0.6]]
W_output_hidden = [[0.3,0.7,0.5],
                  [0.6,0.5,0.2],
                  [0.8,0.1,0.9]]

hidden_input = numpy.dot(W_input_hidden, I)
hidden_output = activation_function(hidden_input)

output_input = numpy.dot(W_output_hidden, hidden_output)
output_output = activation_function(output_input)

print('hidden_input\n',hidden_input)
print('hidden_output\n',hidden_output)
print('output_input\n',output_input)
print('output_output\n',output_output)


hidden_input
 [[1.16]
 [0.42]
 [0.62]]
hidden_output
 [[0.76133271]
 [0.60348325]
 [0.65021855]]
output_input
 [[0.97594736]
 [0.88858496]
 [1.25461119]]
output_output
 [[0.72630335]
 [0.70859807]
 [0.77809706]]


In [44]:
#오차 역전파 값 확인 p105

W_input_hidden = [[3.0,2.0],
                  [1.0,7.0]]
W_output_hidden = [[2.0,3.0],
                  [1.0,4.0]]
e1_output = 0.8
e2_output = 0.5
e_output = [[e1_output],
            [e2_output]]
#W_output_hidden = numpy.transpose(W_output_hidden)
#e1_hidden = numpy.dot(numpy.transpose(W_output_hidden), e_output)
e1_hidden = (e1_output*W_output_hidden[0][0]/(W_output_hidden[0][0] + W_output_hidden[0][1]))+ (e2_output*W_output_hidden[1][0]/(W_output_hidden[1][0] + W_output_hidden[1][1]))
e2_hidden = (e1_output*W_output_hidden[0][1]/(W_output_hidden[0][0] + W_output_hidden[0][1]))+ (e2_output*W_output_hidden[1][1]/(W_output_hidden[1][0] + W_output_hidden[1][1]))

e1_input =(e1_hidden*W_input_hidden[0][0]/(W_input_hidden[0][0] + W_input_hidden[0][1]))+ (e2_hidden*W_input_hidden[1][0]/(W_input_hidden[1][0] + W_input_hidden[1][1]))
e2_input =(e1_hidden*W_input_hidden[0][1]/(W_input_hidden[0][0] + W_input_hidden[0][1]))+ (e2_hidden*W_input_hidden[1][1]/(W_input_hidden[1][0] + W_input_hidden[1][1]))

print('e1_hidden :',e1_hidden)
print('e2_hidden :',e2_hidden)
print('e1_input :',e1_input)
print('e2_input :',e2_input)

e1_hidden : 0.42000000000000004
e2_hidden : 0.8800000000000001
e1_input : 0.3620000000000001
e2_input : 0.9380000000000002
